clients:
  - name: TataCapital
    databases:
      - database: systemx
        host: tclpocdb-ufvqs.tatacapital.tessell.com
        port: 3306
        user: master
        password: Tata123
  - name: Fedfina
    databases:
      - database: atlas_db
        host: atlas-db-uat.c9v4py5vubyn.ap-south-1.rds.amazonaws.com
        port: 3306
        user: master
        password: AtlasDB123##